Repository AlexSandr90/TickTask-backend, pull requests merged in 2025-04, with the labels that each got.

#48 Fixed tables model on prisma
  prisma/schema.prisma
Labels: bug

#49 Remaved field Order from table Task
  prisma/migrations/20250411210622_remove_field_order_from_tesk_model/migration.sql
  prisma/schema.prisma
Labels: bug

#61 fix
  src/modules/auth/auth.controller.ts
Labels: bug

#62 return front
  src/modules/auth/auth.controller.ts
Labels: bug

#64 test
  src/modules/auth/auth.controller.ts
Labels: bug

#66 logaut
  src/modules/auth/auth.controller.ts
Labels: feature

#67 Refactored Users module
  package.json
  src/modules/auth/auth.module.ts
  src/modules/users/users.module.ts
  src/modules/users/users.repository.ts
  src/modules/users/users.service.ts
Labels: refactored

#69 Refactored Swagger for Auth module
  src/common/decorators/swagger/api-response-unauthorized.decorator.ts
  src/modules/auth/auth.controller.ts
Labels: feature, refactored

#70 redirect home
  src/modules/auth/auth.controller.ts
Labels: feature, refactored

#71 Added Auth Guard for Boards module and fix bug with token
  src/common/decorators/current-user.decorator.ts
  src/common/decorators/jwst.auth.decorator.ts
  src/modules/auth/strategy/jwt.strategy.ts
  src/modules/boards/boards.controller.ts
  src/modules/boards/boards.module.ts
  src/modules/boards/boards.repository.ts
  src/modules/boards/boards.service.ts
Labels: bug, refactored

#74 Update auth.controller.ts
  src/modules/auth/auth.controller.ts
Labels: bug, refactored

#75 Smail
  src/modules/auth/auth.controller.ts
Labels: bug

#78 logaut
  src/modules/auth/auth.controller.ts
Labels: feature

#79 Added guards for columns module
  src/modules/auth/strategy/jwt.strategy.ts
  src/modules/columns/columns.controller.ts
  src/modules/columns/columns.repository.ts
  src/modules/columns/columns.service.ts
Labels: bug, refactored

#80 Added auth guard for tasks querys and fixed get all tasks error
  src/modules/columns/columns.controller.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/tasks/tasks.repository.ts
  src/modules/tasks/tasks.service.ts
Labels: bug, refactored

#81 Update user.dto.ts
  src/modules/users/dto/user.dto.ts
Labels: bug, refactored
