Repository AlexSandr90/TickTask-backend, pull requests merged in 2025-05, with the labels that each got.

#82 Added refresh token and refactored auth service. Added repository
  src/common/utils/jwt.util.ts
  src/configurations/app.config.ts
  src/configurations/auth.config.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.repository.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/strategy/jwt.strategy.ts
  src/modules/users/users.module.ts
Labels: bug, duplicate, feature, refactored

#83 Hotfix refresh token
  src/modules/auth/auth.service.ts
Labels: bug

#84 Refactored Auth and Users modules
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.repository.ts
  src/modules/auth/auth.service.ts
  src/modules/users/users.repository.ts
  src/modules/users/users.service.ts
Labels: refactored

#85 Solved problem with refresh token and refactored googleLoginCallback …
  src/main.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/dto/refresh-token.dto.ts
Labels: bug

#86 Removed email from request to refresh token
  src/modules/auth/auth.controller.ts
  src/modules/auth/dto/refresh-token.dto.ts
Labels: bug

#87 Added features for update and delett user avatar
  src/common/constants/index.ts
  src/modules/users/avatar/supabase-avatar.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.repository.ts
  src/modules/users/users.service.ts
Labels: feature

#88 fix(auth): enable cookie passthrough and align cookie deletion options
  src/main.ts
  src/modules/auth/auth.controller.ts
Labels: bug

#89 Added some automation tests for users module
  package-lock.json
  package.json
  src/modules/users/users.controller.ts
  src/modules/users/users.service.spec.ts
  src/modules/users/users.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  test/mocks/index.ts
  test/setup.ts
  test/users.e2e-spec.ts
Labels: feature

#90 fixed bug with refresh token and updated package.json
  package.json
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
Labels: bug

#100 Added position to model and refactored methods
  prisma/migrations/20250528115130_/migration.sql
  prisma/migrations/20250528124735_ad_default_position/migration.sql
  prisma/schema.prisma
  src/common/decorators/boards-api-responses.decorator.ts
  src/modules/boards/boards.controller.ts
  src/modules/boards/boards.repository.ts
  src/modules/boards/boards.service.ts
  src/modules/boards/dto/board.responses.ts
Labels: bug, feature
